### ISSUE TITLE
Trouble configuring on OS X

### ISSUE THREAD

**Issue by rhnorment** [chefArchitect/apispots-testing-bdd#2]
Chef -- 

I love this project, but I'm having trouble configuring this for use on OS X.  I'm a newbie to Docker, which is probably the issue.

It appears I can get the app running in a Docker VM, but I have no idea how to find it in my browser.  I can find other Docker apps in my browser but this one is elusive.

Are there any special OS X instructions?  What LOG information can I attach that will help you help me?

Thanks in advance.

/Hunt

**Comment by xrysanthos** [comment]
Hey Hunt - thanks for the heads up!  I thinks that something is broken in the build cycle so I'll try to carve out some time to investigate the issue.  Now, regarding your OS X question, no there are no specific instructions apart from the Docker installation.  I think this is related to the broken Docker image. 

I'll let you know when it's fixed.  By the way, if you're using NodeJS for development then you can use the project as a library directly and work with it in embedded mode.

Sorry for the hassle :(

**Comment by xrysanthos** [comment]
@rhnorment Just fixed the issues and released a new version.  Should be available in Docker Hub in a while.  Please check again and let me know if you still have any issues.
